# Generated by Django 4.2.7 on 2023-11-12 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Todo title')),
                ('description', models.TextField(verbose_name='Full text todo')),
                ('start_time', models.DateTimeField(verbose_name='Start time')),
                ('end_time', models.DateTimeField(verbose_name='End time')),
                ('bio', models.TextField(verbose_name='Bio')),
                ('status', models.CharField(choices=[('d', 'done'), ('n', 'not yet'), ('a', 'active')], max_length=15, verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'db_table': 'todo_list',
                'ordering': ['start_time', 'title'],
            },
        ),
    ]
