# Generated by Django 4.2.7 on 2023-11-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('n', 'not yet'), ('d', 'done'), ('a', 'active')], max_length=15, verbose_name='Status'),
        ),
    ]
